platform :ios, '8.0'
target 'ConsumeTreasure' do
pod "AFNetworking"
pod 'MSDynamicsDrawerViewController'
pod "RATreeView", "~> 0.9.1"
pod 'HMSegmentedControl@hons82'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod "TSMessages"
pod 'Masonry'
pod 'MJRefresh'
pod 'TTTAttributedLabel'
pod 'JDStatusBarNotification'
pod 'FMDB'
pod 'TPKeyboardAvoiding'
pod 'UMengSocialCOM'
pod 'JSONModel'
pod ‘SDCycleScrollView’
pod 'JPush'
end
